homepage/urls.py
from django.urls import path
from . import views

app_name = 'homepage'

urlpatterns = [
    path('', views.website, name='website'),
    path('gallery/', views.gallery, name='gallery'),
    path('jadwal/', views.jadwal_form, name='jadwal'),
    path('jadwal-output/', views.jadwal_form_output, name='jadwal_output'),
    path('delete/<id>', views.jadwal_delete, name="delete")
    # dilanjutkan ...
]

story/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('homepage.urls')),
    # path('jadwal', include('jadwal.urls')),
 
]

homepage/models.py
from django.db import models
from django.utils import timezone
from datetime import datetime, date


# Create your models here.
class Jadwal(models.Model):
	namaKegiatan = models.CharField(max_length=30)
	hariTanggal = models.DateField()
	jam = models.TimeField()
	tempat = models.CharField(max_length=120)
	kategori = models.CharField(max_length=120)
	deskripsi = models.TextField(blank=True, null = True)


# 	   CREATE TABLE myapp_person (
#     "id" serial NOT NULL PRIMARY KEY,
#     "first_name" varchar(30) NOT NULL,
#     "last_name" varchar(30) NOT NULL
# );

homepage/forms.py
from django import forms
from .models import Jadwal

# class jadwalForm(forms.Form):
#     your_name = forms.CharField(label='Your name', max_length=100)




class jadwalForm(forms.ModelForm):
    class Meta:
        model = Jadwal
        fields = [
            'namaKegiatan',
            'hariTanggal',
            'jam',
            'tempat',
            'kategori',
            'deskripsi',
        ]
# yang ini bikin sendiri forms.py nya

homepage/views.py
from django.shortcuts import render, redirect
from .forms import jadwalForm
from .models import Jadwal
from django.utils import timezone
from datetime import datetime, date


# Create your views here.
def website(request):
    return render(request, 'website.html')

def gallery(request):
    return render(request, 'gallery.html')

def jadwal_form(request):
    form = jadwalForm(request.POST or None)
  
    if (form.is_valid() and request.method == 'POST'):
    	
    # 	form.data['namaKegiatan'] = request.POST['namaKegiatan']
    # form.data['hariTanggal'] = request.POST['hariTanggal']
    # form.data['jam'] = request.POST['jam']
    # form.data['tempat'] = request.POST['tempat']
    # form.data['kategori'] = request.POST['kategori']
    # form.data['deskripsi'] = request.POST['deskripsi']
    	jadwal = Jadwal(namaKegiatan=form.data['namaKegiatan'],hariTanggal=form.data['hariTanggal'],
    	jam=form.data['jam'],tempat=form.data['tempat'],
    	kategori=form.data['kategori'],deskripsi=form.data['deskripsi'])
    	jadwal.save()
    	print(form.data['namaKegiatan'])
    form = jadwalForm()
    context_baru = {
        'jadwal_form' : form
    }
    return render(request, "jadwal_form.html", context_baru)

def jadwal_form_output(request):
    form_output = Jadwal.objects.all()
    context = {
        'jadwal_form_outputs' : form_output
    }
    return render(request, "jadwal_form_output.html", context)

def jadwal_delete(request, id):
    jadwal_delete = Jadwal.objects.get(id=id)
    jadwal_delete.delete()
    return redirect('homepage:jadwal_output')

homepage/templates/base.html
<!DOCTYPE html>
{% load static %}
<html>
<head>

<link rel="stylesheet" href="{% static 'css/stylestory3.css' %}">
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
<link rel="stylesheet" href="{% static 'bootstrap.css' %}">
<link rel="stylesheet" href="{% static 'bootstrap-grid.css' %}">

</head>
<body>
	<div id="navbar">
<nav class="navbar navbar-expand-lg  navbar-dark" style="background-color: #A88279;">
  <a class="navbar-brand" href="{% url 'homepage:website' %}">Felicia Honggo</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav navbar-right ml-auto">
      <li class="nav-item active" id="nav">
        <a class="nav-link" href="{% url 'homepage:website' %}">PROFILE<span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item active" id="nav">
        <a class="nav-link" href="{% url 'homepage:website' %}">EDUCATION</a>
      </li>
      <li class="nav-item active" id="nav">
        <a class="nav-link" href="{% url 'homepage:website' %}">EXPERIENCE<span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item active" id="nav">
        <a class="nav-link" href="{% url 'homepage:website' %}">SKILLS<span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item active" id="nav">
        <a class="nav-link" href="{% url 'homepage:website' %}">CONTACT<span class="sr-only">(current)</span></a>
         <li class="nav-item active" id="nav">
        <a class="nav-link" href="{% url 'homepage:jadwal' %}">ISI JADWAL<span class="sr-only">(current)</span></a>
      </li>
       <li class="nav-item active" id="nav">
        <a class="nav-link" href="{% url 'homepage:jadwal_output' %}">LIHAT JADWAL<span class="sr-only">(current)</span></a>
      </li>
      </li>
    </ul>
  </div>
</nav>
</div>
{% block content %}
{% endblock %}
</body>
</html>

homepage/templates/gallery.html
<!DOCTYPE html>
{% extends 'base.html' %}
{% load static %}

<html>
<head>
<title>My Profile</title>
{% block content %}

<link rel="stylesheet" href="{% static 'css/stylestory3.css' %}">
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
<link rel="stylesheet" href="{% static 'bootstrap.css' %}">
<link rel="stylesheet" href="{% static 'bootstrap-grid.css' %}">

</head>
<body>



<!-- <div id="navbar">
<nav class="navbar navbar-expand-lg  navbar-dark" style="background-color: #A88279;">
  <a class="navbar-brand" href="{% url 'homepage:website' %}">Felicia Honggo</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav navbar-right ml-auto">
      <li class="nav-item active" id="nav">
        <a class="nav-link" href="{% url 'homepage:website' %}">PROFILE<span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item active" id="nav">
        <a class="nav-link" href="{% url 'homepage:website' %}">EDUCATION</a>
      </li>
      <li class="nav-item active" id="nav">
        <a class="nav-link" href="{% url 'homepage:website' %}">EXPERIENCE<span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item active" id="nav">
        <a class="nav-link" href="{% url 'homepage:website' %}">SKILLS<span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item active" id="nav">
        <a class="nav-link" href="{% url 'homepage:website' %}">CONTACT<span class="sr-only">(current)</span></a>
      </li>
        <li class="nav-item active" id="nav">
        <a class="nav-link" href='homepage:jadwal_form'>JADWAL<span class="sr-only">(current)</span></a>
      </li>
    </ul>
  </div>
</nav>
</div> -->



<br>
<br>
<br>

<h1>My Gallery</h1>

<br>

<img id="fotogallery" src="{% static 'images/foto1.jpg' %}" alt="SMAK 6 Goes to UI">
<br>
<img id="fotogallery" src="{% static 'images/foto2.jpg' %}" alt="Foto Saya :)"> 
<br>
<img id="fotogallery" src="{% static 'images/foto3.jpg' %}" alt="Foto Saya :)"> 
<br>
<img id="fotogallery" src="{% static 'images/foto4.jpg' %}" alt="Foto Saya :)"> 
<br>
<img id="fotogallery" src="{% static 'images/foto5.jpg' %}" alt="Foto Saya :)"> 
<br>
<img id="fotogallery" src="{% static 'images/foto6.jpg' %}" alt="Foto Saya :)">
<br> 
<img id="fotogallery" src="{% static 'images/foto7.jpg' %}" alt="Foto Saya :)"> 
<br>
<img id="fotogallery" src="{% static 'images/foto8.jpg' %}" alt="Foto Saya :)"> 
<br>


  <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    
</body>
</html>

{% endblock %}

homepage/templates/jadwal_form.html
<!DOCTYPE html>
{% extends 'base.html' %}
{% load static %}
<html>
<head>
  {% block content %}
<!-- 
<link rel="stylesheet" href="{% static 'css/stylestory3.css' %}">
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
<link rel="stylesheet" href="{% static 'bootstrap.css' %}">
<link rel="stylesheet" href="{% static 'bootstrap-grid.css' %}">

</head>
<body>
	<div id="navbar">
<nav class="navbar navbar-expand-lg  navbar-dark" style="background-color: #A88279;">
  <a class="navbar-brand" href="{% url 'homepage:website' %}">Felicia Honggo</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav navbar-right ml-auto">
      <li class="nav-item active" id="nav">
        <a class="nav-link" href="{% url 'homepage:website' %}">PROFILE<span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item active" id="nav">
        <a class="nav-link" href="{% url 'homepage:website' %}">EDUCATION</a>
      </li>
      <li class="nav-item active" id="nav">
        <a class="nav-link" href="{% url 'homepage:website' %}">EXPERIENCE<span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item active" id="nav">
        <a class="nav-link" href="{% url 'homepage:website' %}">SKILLS<span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item active" id="nav">
        <a class="nav-link" href="{% url 'homepage:website' %}">CONTACT<span class="sr-only">(current)</span></a>
         <li class="nav-item active" id="nav">
        <a class="nav-link" href='homepage:jadwal_form'>ISI JADWAL<span class="sr-only">(current)</span></a>
      </li>
       <li class="nav-item active" id="nav">
        <a class="nav-link" href='homepage:jadwal_form_output'>LIHAT JADWAL<span class="sr-only">(current)</span></a>
      </li>
      </li>
    </ul>
  </div>
</nav>
</div> -->



<br>
<br>


    <br>
    <div id="title">
      <h1>Jadwal Form</h1>
      <form method='POST'> 
      	{% csrf_token %}
        {{ jadwal_form.as_p }}
        <button type='submit' class="save">Save</button>
      </form>
    </div>

   <!--  <br>
    <div id="title">
      <h1>Jadwal</h1>
    </div>
    <div class="container">
   {% for form in jadwal_form_output %}
      <div class="row">
        <div class="col-sm-4">
          Nama Kegiatan :
        </div>
        <div class="col-sm-6">
          {{form.namaKegiatan}}
        </div>
      </div>
      <br>
      <div class="row">
        <div class="col-sm-4">
          Hari Tanggal (yyyy-mm-dd) :
        </div>
        <div class="col-sm-6">
          {{form.hariTanggal}} 
        </div>
      </div>
      <br>
      <div class="row">
        <div class="col-sm-4">
    Deskripsi Singkat :
        </div>
        <div class="col-sm-6">
          {{form.deskripsi}}
        </div>
      </div>
      <br>
      <div class="row">
        <div class="col-sm-4">
          Tempat :
        </div>
        <div class="col-sm-6">
          {{form.tempat}}
        </div>
      </div>
      <br>
      <div class="row">
        <div class="col-sm-4">
          Kategori :
        </div>
        <div class="col-sm-6">
          {{form.kategori}}
        </div>      
      </div>
      <br>
      <br>
    {% endfor %}
    </div> -->

</body>
</html>

{% endblock %}

homepage/templates/jadwal_form_output.html
{% extends 'base.html' %}
{% block content %}
    <br>
    <br>
    <br>
    <div id="title">
      <h1>Jadwal</h1>
    </div>
    <div class="container">
   {% for form in jadwal_form_outputs %}
      <div class="row">
        <div class="col-sm-4">
          Nama Kegiatan :
        </div>
        <div class="col-sm-6">
          {{ form.namaKegiatan }}
        </div>
      </div>
      <br>
      <div class="row">
        <div class="col-sm-4">
           Hari Tanggal (yyyy-mm-dd) :
        </div>
        <div class="col-sm-6">
          {{form.hariTanggal}} 
        </div>
      </div>
      <br>
      <div class="row">
        <div class="col-sm-4">
	  Deskripsi Singkat :
        </div>
        <div class="col-sm-6">
          {{form.deskripsi}}
        </div>
      </div>
      <br>
      <div class="row">
        <div class="col-sm-4">
          Tempat :
        </div>
        <div class="col-sm-6">
          {{form.tempat}}
        </div>
      </div>
      <br>
      <div class="row">
        <div class="col-sm-4">
          Kategori :
        </div>
        <div class="col-sm-6">
          {{form.kategori}}
        </div>      
      </div>
      <br>
      <br>
      <a href= "{% url 'homepage:delete' id=form.id %} "> <button type="submit">Hapus</button></a>
    {% endfor %}
    </div>
{% endblock %}

homepage/templates/website.html
<!DOCTYPE html>
{% extends 'base.html' %}
{% load static %}
<html>
<head>
<title>My Website</title>

{% block content %}
<link rel="stylesheet" href="{% static 'css/stylestory3.css' %}">
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
<link rel="stylesheet" href="{% static 'bootstrap.css' %}">
<link rel="stylesheet" href="{% static 'bootstrap-grid.css' %}">


</head>
<body>

<!-- <div id="navbar">
<nav class="navbar navbar-expand-lg  navbar-dark" style="background-color: #A88279;">
  <a class="navbar-brand" href="{% url 'homepage:gallery' %}">Felicia Honggo</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav navbar-right ml-auto">
      <li class="nav-item active" id="nav">
        <a class="nav-link" href="#brprofile">PROFILE<span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item active" id="nav">
        <a class="nav-link" href="#breducation">EDUCATION<span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item active" id="nav">
        <a class="nav-link" href="#brexperience">EXPERIENCE<span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item active" id="nav">
        <a class="nav-link" href="#brskills">SKILLS<span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item active" id="nav">
        <a class="nav-link" href="#brcontact">CONTACT<span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item active" id="nav">
        <a class="nav-link" href='homepage:jadwal_form'>JADWAL<span class="sr-only">(current)</span></a>
      </li>
    </ul>
  </div>
</nav>
</div> -->

    

<br id="brprofile">
<br>
<br>

<h1 id="profile">Profile</h1>

<br>

<div class="rectangle">
<div class="row">
    <div class="col-4">
    	
      <img id="fotoprofile" src="https://quanta2018.com/Biodata/img/713.png" alt="Foto Saya :)"> 

     </div>
    
    <div class="col">
    <div>
<p id="nama">Felicia Honggo</p>
<p id="penjelasan">Student at University of Indonesia</p>
</div>

<div>
<p id="No HP">Phone : <br>082217659595</p>
<p id="email">Email : <br>feliciahonggo88@gmail.com</p>
<p id="ultah">Date of Birth : <br>25th May, 2000</p>
</div>
</div>
    </div>
</div>

	
<br>
<br>


<p id="hello">Hello ! I'm Felicia!</p>
<p id="description">My name is Felicia Honggo, I'm a 19 years old student who is currently studying in Universitas Indonesia. I love to learn and explore new things and experience. I am a pretty organized, responsible and thoughtful person. </p>



<br>
<br id="breducation">
<br>

<h1 id="education">Education</h1>

<img id="logoui" src="{% static 'images/Logo UI.png' %}" alt="LogoUI"> 

<p id="year">2018 - 2022 (expected)</p>

<p id="major">Majoring in Information System</p>
<p id="courses">Courses taken :<br> 
Introductions to Programming (Python, Java), Discrete Mathematics, Calculus, Basic Foundation of Computer Architecture.</p>

<br>
<br id="brexperience">
<br>

<h1 id="experience">Experience</h1>
<br>
<br>
<div class="row" id="exp">
      <div class="card h-100" id="exp-card">
        <img class="card-img-top" id="top-img" src="{% static 'images/dpm_png.png' %}" alt="Logo DPM FASILKOM UI">
        <div class="card-body">
          <h5 class="card-title">DPM FASILKOM UI</h5>
          <p class="card-text">Head of Secretary</p>
        </div>
    </div>

      <div class="card h-100" id="exp-card">
        <img class="card-img-top" id="top-img" src="{% static 'images/compfestt.jpg' %}" alt="Logo COMPFEST">
        <div class="card-body">
          <h5 class="card-title">COMPFEST</h5>
          <p class="card-text">Staff of Sponsorship</p>
        </div>

    </div>

      <div class="card h-100" id="exp-card">
         <img class="card-img-top" id="top-img" src="{% static 'images/LogoKMBUI.png' %}" alt="Logo KMBUI">
          
        <div class="card-body">
          <h5 class="card-title">KMBUI</h5>
           <p class="card-text">Staff of Creative Events</p>

        </div>  

   
    </div>

  </div>
  <br>
</div>

<br>
<br id="brskills">
<br>

<h1 id="skills">Skills</h1>

<br>
<br>

<div class="container">
  <div class="row" id="skill">

  	<div class="card2">
  <img src="{% static 'images/HTML5-01.png' %}" id="skill-container" alt="Logo HTML" style="width:280px;height:280px">
</div>

	<div class="card2">
  <img src="{% static 'images/css3-01.png' %}" id="skill-container" alt="Logo CSS" style="width:280px;height:280px">
</div>

	<div class="w-100"></div>

	<div class="card2">
  <img src="{% static 'images/py.png' %}" id="skill-container" alt="Logo Python" style="width:280px;height:280px">
</div>

	<div class="card2">
  <img src="{% static 'images/java.png' %}"java.png id="skill-container" alt="Logo Java" style="width:280px;height:280px">
</div>

  </div>
</div>

<br>
<br id="brcontact">
<br>

<h1 id="contact">Contact</h1>

<br>
<br>
<br>
<br>

 <div class="row">
    <div class="col">
    	<a id="facebook" href="https://www.facebook.com/felicia.honggo" target="_blank"> <img src="{% static 'images/facebook-3.svg' %}" alt="Logo FB" style="width:30%" > </a>
    </div>
    <div class="col">
    	<a id="instagram" href="https://www.instagram.com/fel_hong/" target="_blank"> <img src="{% static 'images/ig.png' %}" alt="Logo IG" style="width:30%" > </a>
    </div>
    <div class="col">
    	<a id="linked in" href="https://www.linkedin.com/in/felicia-honggo-988684182" target="_blank"> <img src="{% static 'images/linkedinn.png'%}" alt="Logo Linked In" style="width:30%" > </a>
    </div>
     <div class="col">
     	<a id="twitter" href="https://twitter.com/Fel_Hong" target="_blank"> <img src="{% static 'images/twt.png' %}" alt="Logo Twitter" style="width:30%" > </a>
    </div>
  </div>


<br>
<br>
<br>
<br>

  <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    


</body>
</html>

{% endblock %}